### ISSUE TITLE
Proovisin paigaldada ei õnnestunud

### ISSUE THREAD

**Issue by romilrobtsenkov** [rkajaste/Elemental#11]
Kas peab serveris olema?

<img width="556" alt="screen shot 2017-06-20 at 09 22 08" src="https://user-images.githubusercontent.com/4492641/27319412-ff5e524a-5599-11e7-9110-154d3bbda89a.png">

**Comment by rkajaste** [comment]
Peab olema serveris hetkel. Selleks, et käivitada võrguta olekus peab kõik pildifailid Preload.js skriptis convertima base64 formaadile. Päeva lõpuks üritame ära lahendada. Kättesaadaval on praegu ka lin2 serveris: www.tlu.ee/~rkajaste/Elemental/elemental.html

**Comment by rkajaste** [comment]
@romilrobtsenkov  pildid võtab offline's külge, aga .json faile ei suuda kuidagi külge võtta, proovisin inline kirjutada jsoni kood Preload faili kuid see ka ei õnnestunud. On teil ideid?
